[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"

[build]
publish = "."

  [build.processing]

    [build.processing.css]
      bundle = true
      minify = true

    [build.processing.html]
      pretty_urls = true

    [build.processing.images]
      compress = true

    [build.processing.js]
      bundle = true
      minify = true